// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM4l-CMJUedyfOGn2yWM6JVBmEZhIaYaM',
    appId: '1:292099944624:web:312693216030d09ec30b75',
    messagingSenderId: '292099944624',
    projectId: 'khungulanga',
    authDomain: 'khungulanga.firebaseapp.com',
    storageBucket: 'khungulanga.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4kOIyU3kcp8PpcPRuhynZf_M0qlneDT4',
    appId: '1:292099944624:android:bbc96f9585794299c30b75',
    messagingSenderId: '292099944624',
    projectId: 'khungulanga',
    storageBucket: 'khungulanga.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBldP3Rewm36SNEDTXNDIISaqBAHGpyUpY',
    appId: '1:292099944624:ios:9de1484fb9903ae1c30b75',
    messagingSenderId: '292099944624',
    projectId: 'khungulanga',
    storageBucket: 'khungulanga.appspot.com',
    iosClientId: '292099944624-te23dks8u5gu23a5atsbuo2kjv232lcm.apps.googleusercontent.com',
    iosBundleId: 'com.ictp7.khungulangaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBldP3Rewm36SNEDTXNDIISaqBAHGpyUpY',
    appId: '1:292099944624:ios:9de1484fb9903ae1c30b75',
    messagingSenderId: '292099944624',
    projectId: 'khungulanga',
    storageBucket: 'khungulanga.appspot.com',
    iosClientId: '292099944624-te23dks8u5gu23a5atsbuo2kjv232lcm.apps.googleusercontent.com',
    iosBundleId: 'com.ictp7.khungulangaApp',
  );
}
